FROM mcr.microsoft.com/azure-sql-edge

USER root

# Install prerequisites
RUN apt-get update && \
    apt-get install -y wget ca-certificates

# Install sqlcmd
RUN wget https://github.com/microsoft/go-sqlcmd/releases/download/v1.8.0/sqlcmd-linux-arm64.tar.bz2 -O sqlcmd.tar.bz2 && \
    tar -xvjf sqlcmd.tar.bz2 -C /usr/local/bin && \
    rm sqlcmd.tar.bz2 && \
    chmod +x /usr/local/bin/sqlcmd

ENV PATH="/usr/local/bin:${PATH}"

USER mssql
